### ISSUE TITLE
pagination issue - page 2 displays all docs rather than specific group docs

### ISSUE THREAD

**Issue by vothsco** [boonebgorges/buddypress-docs#479] opened 2015-08-12 19:39 UTC
CBOX member Steve O'Connor reports:
"For each of my groups, when I go to the first page of the Docs, just those from the group are listed. On the second and subsequent pages, the Doc from all groups are listed rather just those associated with the group. I repaired databases, but everything was listed as okay.

WP 4.2.4 cBox 1.0.10"

http://commonsinabox.org/groups/help-support/forum/topic/docs-on-2nd-page-on-list-all-not-just-groups/

**Comment by boonebgorges** [comment] 2015-08-12 21:07
Scott, could you try verifying this on your own installation?

**Comment by vothsco** [comment] 2015-08-13 20:23
Hi Boone - Yes I can reproduce this issue.  I have a group with 11 Docs.  The Group Doc page displays the first 10.  When I click to see page 2, I am taken away from the Group Doc page, and to the  "Docs Directory" page where I see three pages of docs, from all different groups.  I am on page 2, but there are many more than 11.

**Comment by dcavins** [comment] 2015-08-13 20:45
@vothsco, are you using pretty permalinks? What do those pagination links looks like? (Can you give an example of your main docs pagination links as well as a group pagination example?) 

@boonebgorges, we've had and fixed some pagination problems, but those were more general, not specific to groups. Using the 1.8.x/almost 1.9 version of BP, I'm not seeing pagination issues in groups. Could there be an action preventing the group base from being generated?
``` php
// On group Doc directories, modify the pagination base so that pagination works within the directory.
add_filter( 'bp_docs_page_links_base_url', 		array( $this, 'filter_bp_docs_page_links_base_url' ), 10, 2 );
```

**Comment by boonebgorges** [comment] 2015-08-13 20:47
@dcavins It could be something specific to cbox-theme, or perhaps some 
conflict with buddypress-docs-wiki.

**Comment by vothsco** [comment] 2015-08-13 21:15
@dcavins 
this is page 1:
/groups/scotts-group/docs/
then this is page 2:
/docs/page/2/

**Comment by vothsco** [comment] 2015-08-18 13:54
@boonebgorges,
Steve O'Connor is willing to help debug if you point him in the right direction.  See below: 
"Has anything come up about a resolution for this? I've been following the ticket on GitHub. I tried disabling the wiki but that didn't do anything.
I'm not the sort to dump things on other's laps, so if you can offer any suggestions, I'll be glad to poke around and try things out. I'm not afraid to mess around with some code (but I am not a coder)."

Thanks!

**Comment by boonebgorges** [comment] 2015-08-18 13:58
Hi @vothsco - I'm going to try to look at it this week. Please let Steve 
know that the dev team is very busy, so it's difficult for us to address 
problems immediately, but that it's on our radar. Thanks.

**Comment by boonebgorges** [comment] 2015-08-21 02:08
This should be fixed by 5450c1c13f4f67aa9ca93e4cf047eb3143c2973f and 9d3c1560d805e78dfc9057f82503cc89c9191be7. It'll be part of the impending buddypress-docs bugfix release, and will also be part of the next commons-in-a-box release. @vothsco, please encourage Steve to update his buddypress-docs installation manually (after tonight's release) if the problem is so severe that he doesn't want to wait for Commons In A Box to get a bump. Thanks!

**Closed by boonebgorges** 2015-08-21 02:08 UTC

**Comment by stevejoc** [comment] 2015-08-22 16:38
I updated buddypress-docs via ftp. All good now! Thanks Boone!

Hundreds of teachers use this site to grab free multimedia lessons delivered to thousands of children. People like you make this possible.

**Comment by boonebgorges** [comment] 2015-08-22 17:28
Happy to hear it :) Thanks, Steve!
