### ISSUE TITLE
HTML Formatting Issue on Version Comparison

### ISSUE THREAD

**Issue by mkgold** [boonebgorges/buddypress-docs#133] opened 2011-08-26 14:21 UTC
While comparing two versions of a document, I saw that HTML tags were included in the document as plain text rather than being rendered by the browser. I'll send along a screenshot (don't think I can add attachments here)

**Comment by boonebgorges** [comment] 2017-11-15 03:54
It's hard to argue with my "feature not a bug" wisdom of those many years ago. Closing to clear out the backlog.

**Closed by boonebgorges** 2017-11-15 03:54 UTC
