### ISSUE TITLE
Docs list page won't show a sub folder

### ISSUE THREAD

**Issue by bwk1224** [boonebgorges/buddypress-docs#748] opened 2024-03-04 23:00 UTC
The system is currently using BuddyPress Docs version 2.2.1 plug-in.

A user of a private group submitted a ticket that the following stopped working few months ago.

When trying to view a sub folder of a folder within the private group documents page, the program generates 0 results, causing the list table to be empty.

For example:

    Folder 1
        Sub-folder 1 to Folder 1
        Sub-folder 2 to Folder 1
        Sub-folder 3 to Folder 1
        Sub-folder 4 to Folder 1
        Sub-folder 5 to Folder 1
    Folder 2
        Document 1
        Document 2
    Folder 3
    Etc.

The "Folder 1" shows an empty list when expanded on the documents list page. However, when there's only documents under a folder(Ex. folder 2), the list is generated properly.

The user claims that the folder 1 used to show its sub folders before.

Is this a program design change or a bug? If it's a program design change, how can I make this work as before?

Thanks.

**Comment by bwk1224** [comment] 2024-03-05 18:03
Hello, the version 2.2.2 didn't solve the issue.

Here's the sample setup that you could try.

The site has multiple private groups. Let's focus on group A.

User A is the group administrator of the group A.

The group A's "Documents" settings have the following options set.
- Enable Docs for this group = Checked
- Minimum role to associate Docs with this group = Group admin

All folders and documents were uploaded by the user A.

Folder permissions
- Folder 1 (main folder)
-- Parent: None
-- Type: Group specific: Group A
- Folder 1-1 (sub folder)
-- Parent: Folder 1
- Folder 1-1-1 (sub folder of sub folder)
-- Parent: Folder 1-1
- Folder 1-2 (sub folder)
-- Parent: Folder 1
(..and so on... This particular Folder 1 has 34 sub folders, and about 6 of them have their own sub folder.)
- Folder 2 (main folder)
-- Parent: none
-- Type: Group specific: Group A
- Folder 3 (main folder)
-- Parent: none
-- Type: Group specific: Group A
- Folder 3-1 (sub folder)
-- Parent: Folder 3
And so on... 

There are 90 total main and sub folders under this private group. Each folder has random number of documents.

The issue of showing sub-folder contents occurs on the following page: https://abcd.com/groups/A/docs/
Spinner shows when a folder 1 is clicked to expand the view, but no sub folders show. A empty table list is returned.

Going to the folder 1 page directly shows all sub-folders correctly for all private group members. Ex. https://abcd.com/groups/A/docs/?folder=xxxx(ID of folder 1).

No wordpress account (even the system administrator) can view the list correctly now on the docs list table page. 

Please let me know if you need additional information.

**Comment by boonebgorges** [comment] 2024-03-05 18:14
Thanks so much for the extremely helpful details. I'll try to reproduce this soon.

In the meantime, your note about the "spinner" stood out to me. It suggests that there's a failed AJAX request taking place. Can you monitor your Network tab to see whether that's the case? Or is there anything in your PHP error log indicating, say, a fatal error associated with these AJAX requests?

**Comment by bwk1224** [comment] 2024-03-05 18:22
When requesting a folder 1 list, the network got 200 for this request url.
https://abcd.com/wp-admin/admin-ajax.php?lang=en&bpml_filter=true&folder=xxxxx&group_id=x&user_id=0&action=bp_docs_get_folder_content

But when a table is inspected, the table with ".doctable" class generated a tr row with "no-docs-row" class.

I didn't see any error msgs related to docs. I did see an error log for the buddypress/menu-notifications.php, but I don't think this is related.

**Comment by boonebgorges** [comment] 2024-03-05 19:47
@bwk1224 Thanks for your detailed feedback. I was able to reproduce this with the right configuration and versions of BP.

@dcavins As noted above, I think the problem is that in BP 12, `bp_is_group()` and friends doesn't work right in AJAX callbacks. This seems like a pretty big bug in BP not to have been caught previously, so I wouldn't be surprised if it's something specific to the way buddypress-docs works. Anyway, I built a "get current group ID" wrapper function in e0b3c54 that works in AJAX by deriving the group ID from the passed URL. The technique used is pretty wacky, but I couldn't find a tool in either BP or WP for matching and parsing rewrite rules. (WP-CLI does something not dissimilar so I'm guessing this is as good as it gets https://github.com/wp-cli/rewrite-command/blob/293f9de9905b9d0199d72ff0d17e837228e47a10/src/Rewrite_Command.php#L237) Could you have a look?

**Comment by dcavins** [comment] 2024-03-05 19:54
Yes, I'll look at your patch and also keep thinking about this generally. If BP is failing at this generally, we need to fix it there.

**Comment by boonebgorges** [comment] 2024-03-06 02:48
After feedback on how this is supposed to work in BP 12+, I've updated my branch. See https://github.com/boonebgorges/buddypress-docs/pull/750/files. @dcavins Can you please review before I push this out?

**Comment by dcavins** [comment] 2024-03-06 03:23
@boonebgorges I've tested this on my local site that I was able to recreate the problem on, and it does resolve the problem. It should resolve a lot of problems (that we didn't know we had?)! Thanks @imath!

Code looks good, too. Thanks for the quick resolution!

**Comment by boonebgorges** [comment] 2024-03-06 18:23
Thanks, all. This issue should be fixed by the 2.2.3 release, which I've just pushed to wordpress.org.

**Closed by boonebgorges** 2024-03-06 18:23 UTC
