### ISSUE TITLE
Attachment Corrupt on download

### ISSUE THREAD

**Issue by briankrm31** [boonebgorges/buddypress-docs#439] opened 2015-01-21 18:02 UTC
Hello,
WP ver. 4.0.1
BP ver. 2.0.1
BP Docs ver. 1.8.1
Server Windows OS 2008

My problem. I am having a problem when I download a attachment, and then try to open it. I recieve a mess corrupt file or a message that says the file cannot be read or not supported.??

When I go on the server to the actual file it is not corrupted. Also, I have tried the most current version of Buddypress Docs and I receive the same result. I also have copied the whole website to a linux test environment and it works without a problem. The media library works fine on the windows server.

Any help?

**Comment by vothsco** [comment] 2015-04-11 15:26
Hi - this issue was also noticed by CBOX member August West:
" My site is a WordPress 4.1.1 site running Multisite, BuddyPress and CBOX, version 1.09.

In a BuddyPress private group, when I add a Microsoft Word file as an Attachment to a Wiki using BuddyPress Docs, then try to view, I receive a message:

‘file cannot be opened because there are problems with the contents’

When I click thru the message it returns:

‘Word found unreadable content in x [file name]. Do you want to recover the contents of this document? If you trust the source of this document, click Yes.’

When I click Yes, Word displays the content, but this is not very user-friendly behavior and the file cannot be then edited and saved.

I can add and open PDFs thru BP Docs Attachments, but not Word files (doc or docx). The Word files open OK locally so they are not technically corrupted."

I tried this on my test site, on a public group and noticed that too - they eventually open, but after a lot of ugly warnings.

**Comment by vothsco** [comment] 2015-04-11 15:30
Here is a link to the thread on cbox.org - http://commonsinabox.org/groups/help-support/forum/topic/bp-group-docsms-word/#post-5584

**Comment by boonebgorges** [comment] 2015-04-13 14:37
@vothsco Can you please say more about exactly how you opened the file? When you clicked the link, did it open directly in Word? Were you asked whether you wanted to download or open? If so, which did you choose? Did you test with the other method? What is your OS?

**Comment by vothsco** [comment] 2015-04-15 00:43
I was using Windows, but also tried in Mac, which was a little smoother, but still had the following warnings,after preliminary warning from anti-virus:
-- 
![download ms warning](https://cloud.githubusercontent.com/assets/630806/7150265/8a441328-e2e6-11e4-8148-d38a881fd362.PNG)
![ms warning 2](https://cloud.githubusercontent.com/assets/630806/7150266/8a45ce34-e2e6-11e4-9c96-7e11b308aed8.PNG)

-- file cannot be opened because there are problems with its contents
-- Word found an unreadable content in ***.docx. Do you want to recover the contents of this document? If you trust the source, click yes.

 I have attached screenshots of the messages.  As I said, if you just click through all these messages, everything works fine.  Maybe it is MS issue?

**Comment by boonebgorges** [comment] 2015-04-15 12:32
Hm. It's probably a Docs issue, but I can't seem to reproduce it exactly. Could you send me a copy of a file that you've downloaded that's given you the problem? And could you clarify: are you clicking directly to open it, or are you first downloading and then opening from your desktop? If the former, does doing the latter clear up the problem?

**Comment by vothsco** [comment] 2015-04-16 01:56
Hi Boone - For me it doesn't seem to make a difference - if I choose download or open I still get the two sets of warnings - but  as I said - everything works fine if you just click through them.  I tried attaching a test file, but file type seems restricted - so below is a link to a simple docx file created in Windows 

https://www.dropbox.com/s/cy92exwbb6jl11p/This%20is%20a%20test%20docx%20file.docx?dl=0

**Comment by boonebgorges** [comment] 2015-04-17 10:43
Thanks for the file - I still can't manage to reproduce, but maybe it's 
because of some problem with my word processing software. What version 
of Office are you using?

**Comment by vothsco** [comment] 2015-04-17 12:57
On Windows, I was using Office 2007.  On Mac I was using Office 2011.

**Comment by boonebgorges** [comment] 2015-04-20 13:16
Thanks, @vothsco. I'm going to try to rustle up a couple copies of 
Office so that I can reproduce. In the meantime, if you're able, could 
you enable debugging on your server https://codex.wordpress.org/WP_DEBUG 
and let me know if any errors correspond to the file download?

**Comment by vothsco** [comment] 2015-04-21 14:27
Hi Boone - I turned on debug - got a lot of "Strict Standards" errors - but ignored them and tried to download a docx file.  I don't know if this will help - but this is what I am seeing when I click on the attachment icon:

Strict Standards: Declaration of ICE_Posts_List::single_row() should be compatible with WP_Posts_List_Table::single_row($post, $level = 0) in /home2/svothcom/public_html/cbox107/wp-content/themes/cbox-theme/engine/ICE/ext/widgets/posts-list/class.php on line 259

Notice: Undefined property: WebAvenue_Activity_Widget::$plugin_id in /home2/svothcom/public_html/cbox107/wp-content/plugins/buddypress-activity-sidebar-widget-resubmission/buddypress-activity-widget.php on line 92
PK!���7f [Content_Types].xml �(��T�n�0�W�?D�V������8�H�`� X�K����nDUA*�)Y����ă�ښl 1i�J�/z,'��nV���K~ϲ��)a���m ����j0�Hu�T�9bx�<�9X� �Q��� ��8�A�O1~���q���k6$N{9���+P9Y ��vu�GD����oR��w�ͳ� �Iʊ~���8��W�Z�"V0}����������>����uQwHo����PK!���N_rels/.rels �(����JA���a�}7� "���H�w"����w̤ھ�� �P�^����O֛���;�<�aYՠ؛`G�kxm��PY�[��g Gΰino�/<���<�1��ⳆA$>"f3��\�ȾT��I S����������W����Y ig�@��X6_�]7~ f��ˉ�ao�.b*lI�r�j)�,l0�%��b� 6�i���D�_���, � ���|u�Z^t٢yǯ;!Y,}{�C��/h>��PK!�d�Q�1word/_rels/document.xml.rels �(����j�0���{-;���ȹ�@��������$���~� CR���`Fh擴��wo�'�U�%)���:�(x/vw� ����qH��oo6�h4�C�v�DL���e�k)�l�ה8�6��.�������� �U�>�0̀�"S�+a_݃(���vuݕ���c���T�/<�!s��Xd3�� �����?'g![�?��4���%�9����R�k6��$C�,�`&g�!/=���PK!����word/document.xml�T�n�0��?�ے��Vu�S��N?��VQ�K���뻤$�i�� H\.gv�A�^Z��:�z�fӌ%��R������%�s]r�6��=�?���DqhA��(�ˏ�m�7y�:�@�� hrVh[�ɴu�r��`&[ý�K%�)�g�-hp�V�Ť�¢��H�U%�a���#���1��Hj�H�F���l�b3��K�ت�\g��VZ�Q?Z���ЖƢ�hw�;ό���C�q���1G%-��L�����7��}�4P�&B�(h��X���$]N�X�ذ,[-g7_l��B���|��_�"�X���.H�����ύt =<��|�N�d�D5���Z��'C@g@���ֳ4������U�G]^�@��)����>dB<�?9�����u���w� ��՝ϗty������c���c�H�6[�G��b�=z�4������6�K�;��G� �_���Gs'P9�0t"@� *�7+K�(��IzA*��K������@{�ߥ���PK!����Pword/theme/theme1.xml�YOo�6��w toc'vu�ر�-M�n�i���P�@�I}��úa��m�a[�إ�4�:lЯ�GR��X^�6؊�>$���������!)O�^�r�C$�y@�����/�yH*��񄴽)�޵��߻��UDb�`}"�qۋ�Jח���X^�)I`n�E���p)���li�V[]�1M<������O�P��6r�=���z�gb�Ig��u��S�eb���O������R�D۫����qu �g��Z����o~ٺlAp�lx�pT0���+[}`j�����zA��V�2�F���i�@�q�v�֬5\|��ʜ̭N��le�X�ds���jcs����7����f���� ��W���+�Ն�7����`���g�Ș��J���j|��h(�K��D-���� dX��iJ�؇(��x$(��:��;�˹!�I_�T��S1�������?E��?������?ZBΪm���U/������?�~����xY����'���y5�g&΋/����ɋ�>���G�M�Ge���D�����3Vq%'#q�����$�8��K�����)f�w9:ĵ�� x}r�x����w���r�:\TZaG�*�y8I�j�bR��c|XŻ�ǿ�I u3KG�nD1�NIB�s��� ��R��u���K>V�.EL+M2�#'�f��i~�V��vl�{u8��z��H� �*���:�(W�☕ ~��J��T�e\O*�tHG��HY��}KN��P�*ݾ˦���TѼ�9/#��A7�qZ��$*c?���qU��n��w�N��%��O��i�4=3ڗP�� ����1�P�m\\9���������Mؓ�2a�D�]�;Yt�\����[x������]�}Wr��|�]��g-��� eW� �)6-r��CS�j�� i�d �DЇA�ΜIqbJ#x�꺃6k���#��A�Sh��&ʌt(Q�%��p%m��&]�caSl=�X�������\P�1�Mh�9�M��V�dDA��aV�B��[݈fJ�íP|8�քA�V^��f �H��n���-��"�d>�z���n��Ǌ� �ة�>�b���&����2��v����Kyϼ���D:����,AGm��\nz��i�Ù��.uχYC�6�OMf��3o�r��$��5�����NH�T[XF64�T,ќ���M0�E)`#�5�XY�`�פ;��%�1�U�٥m;���R>QD����D�cp�U�'��&LE�/p���m���%]�����8fi��r�S4�d7y\�`�J�n���ί�I�R���3U�~7+���׸#��m�q�BiD����������i*�L6�9��m�Y&�����i���HE��=(K&�N!V��.K�e�LD�ĕ�{D ����vEꦚde��NƟ��e�(�MN9ߜR�6����&3(��a����/D��U�z�<�{ˊ�Y��ȳ����V���)�9�Z[��4^n��5���!J��?��Q�3�eBo�C����M����m<�.�vp�����IY�f���Z�Y_p�[�=al-�Y�}Nc͙���ŋ4vfa��vl����'S���A�8�|�*u�{��-�ߟ0%M0�7%����<���ҍ���PK!��&�/word/settings.xml�T�n�0}��@ ���L�<^�qDe��M��]/N��:���4��Ɨ�ߝ���Ρ��PB�L�qgdf�� ��*���ݢR"Su�*:}�a�uNgI2�����je8{�L���+Uu�J����81��Àm˴ j���6��_Kb/x���k�S��2���	�(�ѿ���έ�ŭ6v_Y� DjV��O��l�uԉE]���;+�Bڠ��v�2e<�>�w���y��q� �(\��{9%��E�Z"�B%]V\�X �R�����){��͆y%Jو�պWbjʯ��3��j��i�D�և��N�}��~�Hl���:x7 <�k"1��1�h��"b[ߖ�D�U??M��Q������Df��>�Y��h��hx ����7��ࣞ�7�6 ���d� .���PK!J؊��word/webSettings.xml���j�0��{a�t_��0JHR(�/��\Gi�d$m���5l��z����_im>Q42 �m�A -h�;q�6���?��PK!d�pEwdocProps/core.xml �(���_K�0���C�{�d�CJہʞ�(���n6H�}{�v�����9��soR,��N�4�D4#(͍�zW���2�G�LV %:�G�����6����3\���H�>�D�l���{P�gѡ��5N�K�Ö�O��LW�����:'�7�����_����PK!�����9word/styles.xml���s�8��o����!M��!0���� i�[�58V�Rh�_��V];�wk�D�C�YiW�u���ۻ]��2[���'a��H�"�Y��W��J�,f���*��*|���?^ߞ*}�r�:�Wa���t2QQ�wL=�{��g[��6���Dn�"��et��LOf''�I�S� \%b����-�ڭ��}.#���v�:{;&���q/��{�e�T+{�_��eq�|��V��)S�W�q3ŝ�d��,S"4O8S�L v�ab�:�$R�b흈E8�D������U8��wέ��,�)��������*��6��*d����56�i��V��4ys��Yd�p�Vs@�I� �l�(/�Rs��, `���f�em�M\M��.K�S��,�<^k�`�ܼ��̅̅�_��^Y����;�I�1�IYܻ���]+?���R���C����%dA��w��3�3f#��H�YU�C����Q����J����(%��n������A3;���.���p/��x9�$ﰵX��Ј�ܨd%>�ZF.���0Ց�vD#�zG4��wD#GzG4R�wD#zG4�;����pv��W=����}%t���N������,g79�'�-�u���r}�h�� �O˵�evӻ"�:ۭ�dM���'L �Eӳ���K�6)��E܋z钯1'�09Z�.S�D�1σ+~�"J�Uk�������~7�� ��^آe��W���,�A�fZ�L��8*����l7����+��5�pzNs .v/����ꝅ f �\Ч����B�oc��ߕ�'�G�� ��C~tǗ�4�Y�#@m�%y��T��CZ�^yX�w�G�@���>J$���H>��(2��a��%P��p�l����R��)aF��X3k��@d��� ��'j1��ߚ��y޲�����������h�r��?�(�h󖝇����!�� 4�@�J!Ԓ��<�&�!Ë#�E�e_� ��ʼ$+��J�Hu��ղ{�s�Y7r��uA!G�V�|�D�F��VK�h�QUS)�"��*� f4�x#@�74�x#@�Ż2�x#Xdm�Zo^����AU�F����Ԯ��QY��J�/�#�7�BPS�rt����W(�Pcy�C��oh�F��oh�F��oh�x�C�o�� ^S���������+m8*ް��x#(�5�A!G�&��#�"����`�+�d(X�ܔI�#ވ�#��8��#��p�'�Y��V�"˃U�"k�Q�����A!�)� 9:5A�:�`�Tcy�F� _�7�<D��8⍘�8��#��p�'�Y��V�"˃U�"k�Q�=���A!�)� 9:5A��`�Tcy�C��os�x#@��@��(aG�3G�����O�,�6xM��7D���7D�{�֜EO��$��Ay� �� ,&��oyn:�x�鐁�r�bKz`��N��`��%A�(�I��#��pJ�҈0_vt\�s|r 0�q�R�Oޘ�j��'��!㧾ߛ��}y��Z3 B���h�>��T������ǼMU�m�ۂ ?����|��d�b��|^48�ɦQb��L�T��Qx: ��]j9/n=4k�������{�No�[f [����x��p��s�x�Ż�i���<���m�I]#���"��0m�k.��sf��s��_��i�o5�[�NO�N�Lm��r�>>�c���1f��θK;����� �MX�����@����u'b]���3�C^cW����'����PK-!���7f [Content_Types].xmlPK-!���N�_rels/.relsPK-!�d�Q�1�word/_rels/document.xml.relsPK-!�����word/document.xmlPK-!����P4word/theme/theme1.xmlPK-!��&�/�word/settings.xmlPK-!�ފ���word/fontTable.xmlPK-!J؊���word/webSettings.xmlPK-!!&_v��docProps/app.xmlPK-!d�pEw@docProps/core.xmlPK-!�����9�word/styles.xmlPK��#
Notice: Undefined property: WP_Error::$slug in /home2/svothcom/public_html/cbox107/wp-includes/class-wp-error.php on line 78

Strict Standards: Only variables should be passed by reference in /home2/svothcom/public_html/cbox107/wp-content/themes/cbox-theme/engine/includes/WPThumb/wpthumb.php on line 209

**Comment by boonebgorges** [comment] 2015-04-22 14:07
Thanks, @vothsco. This makes it look like it might be related to the 
cbox-theme specifically, though I still can't reproduce.

Could I ask you to try something? In 
wp-content/plugins/buddypress-docs/includes/attachments.php, find the 
`catch_attachment_request()` method. Just before the line that reads 
`$headers = $this->generate_headers( $filepath )`, put the following:

     error_reporting( 0 );

See if that has any effect on the downloaded file.

**Comment by vothsco** [comment] 2015-04-22 23:12
Hi Boone - that change did seem to help with when I click on the attachment and select "Save".  That totally works.  But got the same errors when tried to open the file.The default program is the MS XML Open Converter - see screenshot.  But still get those errors but it ultimately works.
![dl2](https://cloud.githubusercontent.com/assets/630806/7287488/17a9e07a-e923-11e4-87c2-cead112911c5.PNG)

**Comment by boonebgorges** [comment] 2015-04-23 11:54
@vothsco Can you clarify this last comment a bit? In your earlier report, was Microsoft Open XML Converter the program that Windows was using to open the file? Are the errors you see with that program exactly the same ones you see when you open in Word? When you say "that change did seem to help when I ... select "Save"", do you mean that you're able to download the file now, and open it from the desktop, without any errors? What program opens the file from your desktop - Word or the XML Converter?

Side question: Have you tried uploading this file from Dashboard > Media and then downloading from there? Do you get the same problem?

**Comment by vothsco** [comment] 2015-04-23 12:40
Yes, when I click on Open - the default program is MS Open XML Converter and it seems to cause the problem and throw the errors.  I never really get to Word until I click through the errors - and then it works fine.  After the change you asked me to implement, when I click on Save - everything seems to work flawlessly - no error messages.
When I added via dashboard>>Media and included it on a post, and then downloaded it, I did not get the error messages.  It opened correctly in Word.

**Comment by boonebgorges** [comment] 2015-04-24 12:48
Can you tell me more about your WP configuration? Is this a multisite 
setup? Are you logged in as an administrator?

**Comment by vothsco** [comment] 2015-04-24 13:19
It is not a multisite and I am logged on as an admin.  I just created a whole new site for testing new version of CBOX - using the new codebase - and the problem seems to be resolved.  Docx files open correctly now.  Maybe you put in a fix?  I was running the version of CBOX from the WP repo previously and that had the problem.

I think we can close this ticket once new version is released - or whatever you think.  Thanks!

**Comment by boonebgorges** [comment] 2015-04-24 13:21
Very weird. It is possible that this is related to some issue that's already been resolved. Since your old install is running an out-of-date version of Docs, and the new one is running the latest, let's tentatively close this ticket. If the issue crops up again, we'll pick up the thread then. Thanks for your help troubleshooting.

**Closed by boonebgorges** 2015-04-24 13:21 UTC
