### ISSUE TITLE
Problems with Attachments - Re-opening issue 439

### ISSUE THREAD

**Issue by vothsco** [boonebgorges/buddypress-docs#454] opened 2015-05-04 02:34 UTC
Hi  -
We recently closed issue 439 - (https://github.com/boonebgorges/buddypress-docs/issues/439) but 
CBOX member August West reports that the issue is not resolved.  He installed the latest version of CBOX and still encounters the same issue. 

When I tested, I tested with a brand new install of CBOX and everything seems to be corrected - Docs downloads the docx file and when you click it opens properly in Word - no problem.

However, after reading August's post, I upgraded my old CBOX site to new version of CBOX (upgraded CBOX, CBOX theme, cleared my cache) and I see the same issue that August reported (http://commonsinabox.org/groups/help-support/forum/topic/bp-group-docsms-word/) – docx attachments get numerous warnings and open with the wrong program – but ultimately works. 

So on fresh installs of CBOX everything is good - on upgrades of CBOX, the issue persists.

**Comment by boonebgorges** [comment] 2015-05-04 11:54
@vothsco - Is it limited to new vs old attachments? Ie, those uploaded 
before the upgrade vs those uploaded afterward?

When you updated commons-in-a-box, did you also update the theme to the 
latest? If not, does that make a difference?

**Comment by vothsco** [comment] 2015-05-04 12:23
I tried adding a brand new doc and brand new attachment, but it didn't make a difference.  When I upgraded, I upgraded both CBOX and its theme, also cleared cache and tried on different browswer - no difference.

**Comment by boonebgorges** [comment] 2015-05-04 12:28
Are the two installations in exactly the same hosting environment, and 
with the same commons-in-a-box configurations (eg, other plugins 
activated)? It's not clear to me how the mere fact of being an upgraded 
site would cause any problems - makes me wonder if there is a plugin 
conflict.

**Comment by vothsco** [comment] 2015-05-05 00:45
Hey Boone - same hosting but definitely different setups.  I just deactivated all the plugins on my old site (the one I upgraded) but saw no change.  The issue persists.  I created a new doc, then created a new attachment - that didn't change anything,  It seems like a very strange issue.

Also - August West (http://commonsinabox.org/members/awest/) is willing to do some testing, as he is most affected by this issue - http://commonsinabox.org/groups/help-support/forum/topic/bp-group-docsms-word/#post-5624

Good to include him on any tests requests.  Thanks.

**Comment by AWest99** [comment] 2015-05-05 22:54
Hi, I'm August West. For reference, here's the issue:

In a BuddyPress private group, when I add a Microsoft Word file as an Attachment to a Wiki using BuddyPress Docs, then try to view, I receive a message:

‘file cannot be opened because there are problems with the contents’

When I click thru the message it returns:

‘Word found unreadable content in x [file name]. Do you want to recover the contents of this document? If you trust the source of this document, click Yes.’

When I click Yes, Word displays the content, but this is not very user-friendly behavior and the file cannot be then edited and saved.

I can add and open PDFs thru BP Docs Attachments, but not Word files (doc or docx). The Word files open OK locally so they are not technically corrupted.

Also, if I happen to hardcode in HTML a link to a Word doc (uploaded to the Media Libary thru Add Attachment) in the CONTENT section of a BuddyPress Doc, it will open without error messages. The errors appear when I try to open a Word doc uploaded through Attachments and displayed under Attachments in a BP Doc.

Before this issue surfaced, SSL was enable sitewide, but I’ve since rolled back to http but the problem remains. With my local instance of XAMP / WordPress / CBOX, Word docs open OK in a group using BP Docs. 

The application/msword MIME type (doc docx) is enabled at the server level on the live site.

My next step is to look at other plugins (WordFence, etc.).

Please let me know if you need more information and thanks!

**Comment by vothsco** [comment] 2015-05-06 01:30
For the record - I thought August was referring to Docs created within a regular group (Buddy-Press_Docs), not the wiki (BuddyPress-Docs-Wiki).  But I find that issue exists on BuddyPress-Docs as well - (but only on upgraded sites).

Boone - if it helps, I can share my site where the issue occurs.  Maybe that would help you debug?  (My site is pretty beat up from testing issues, but hopefully can help.)

**Comment by AWest99** [comment] 2015-05-12 17:30
@vothsco -- Sorry for the confusion re: wiki. Actually, I'm using BuddyDocs as you are, we are just referring to it as a 'wiki' internally. We are trying to convert a wikispaces wiki into a BuddyDocs–based wiki, with the Attachment issue described above as the only sticking point.

We are seeing some demand from wikispaces users whose sites need to find a new home. BuddyDocs, on the surface, seemed like a good alternative.

Back to the Attachments issue, could .htaccess have a role in this issue? I read here:

https://github.com/boonebgorges/buddypress-docs/wiki/Attachment-Privacy

that AllowOverride is needed, but not sure of the exact syntax for htaccess.

I can also invite someone to the group that is having this issue if that helps.

**Comment by AWest99** [comment] 2015-05-16 13:49
FWIW, I was testing BuddyDrive and ran into the same Word error messages as described above when placing BuddyDrive links in posts. I found this addressed in a support page and added

ob_end_clean();

as shown on this page –- https://wordpress.org/support/topic/corrupt-files-delivered-through-php-buddydrive-needs-ob_clean-or-ob_flush

After making the change, BuddyDrive Word docs now open without errors.

**Comment by vothsco** [comment] 2015-05-16 22:00
Hi @boonebgorges - 
Wondering if @AWest99 's fix for BuddyDrive for this issue might work on CBOX?  Or if any further ideas?

**Comment by boonebgorges** [comment] 2015-05-17 00:46
@AWest99 Thanks for your comment.

@vothsco Can you test it please? It's hard for me, as I can't reproduce the issue to begin with. In buddypress-docs/includes/attachments.php, change the following line:

    readfile( $filepath );

to 

    ob_flush();
    readfile( $filepath );

(It's around line 88, in the `catch_attachment_request()` method.)

**Comment by vothsco** [comment] 2015-05-17 15:20
@AWest99 @boonebgorges
Hi - I tried the change - there was a slight difference in Chrome - file was downloaded, but when I tried to open it I still got those messages.  In Firefox and IE, it did not make a difference.

**Comment by AWest99** [comment] 2015-05-18 16:39
Hi -- thanks for the messages. I was getting similar results as vothsco, then I placed 

ob_end_clean();

where Boone inserted ob_flush

and good results so far - Word attachments added to Docs using the Attach function are opening OK. FWIW, I'm not a PHP programmer and don't know the potential consequences of this code and/or if this is a sustainable option for future iterations, etc.

I will do more extensive testing on the front end w/ other browsers today and will report back -- thank you again.

**Comment by boonebgorges** [comment] 2015-05-20 19:50
Thanks @AWest99! @vothsco, can you try the same thing?

**Comment by vothsco** [comment] 2015-05-21 02:39
@AWest99 @boonebgorges -
I tried replacing that snippet, as August described, but it did not seem to work for me -  I still got the same issues, even after clearing cache.

**Comment by cspurrier** [comment] 2015-07-10 19:54
Adding die() right after readfile fixed it for me.

**Comment by boonebgorges** [comment] 2017-11-18 20:50
Since the fix worked for the original reporter, and we haven't heard new reports of the issue, I'm going to close this one.

**Closed by boonebgorges** 2017-11-18 20:50 UTC
