### ISSUE TITLE
Change select option to checkbox in associated group

### ISSUE THREAD

**Issue by maciejbuchert** [boonebgorges/buddypress-docs#531] opened 2016-03-21 12:38 UTC
Hello I want to change select list to checkbox in associated group, because I want to share doc with more than one group.

Can you help me ?

**Comment by dcavins** [comment] 2016-03-21 14:07
Hi Drozdz-

I think we'd all like to share docs with multiple groups, but we haven't yet worked out a user interface for this situation that isn't overwhelming. As a result, we only support associating a doc with a single group.

-David

**Comment by drozdz** [comment] 2016-03-21 15:08
Thanks for ansrew.

But when I edited the doc from wp-admin panel I could add more then one group.

**Comment by boonebgorges** [comment] 2017-11-15 16:18
Going to close this one as a duplicate of #124 and #223.

The inconsistent view in wp-admin is something we would like to fix; follow #118 for more info.

**Closed by boonebgorges** 2017-11-15 16:18 UTC
