### ISSUE TITLE
Directory - Browse by attachment status bypasses access protection

### ISSUE THREAD

**Issue by trans1t** [boonebgorges/buddypress-docs#472] opened 2015-07-07 20:30 UTC
In the directory, if browsing by "has attachment" status (eg. at the endpoint `/docs/?has-attachment=yes`), private docs are shown in the results.  You can't access the individual docs but you can see the 'blurb' which may contain sensitive information.

This seems to be because the post type with the has-attachment url param switches the post type being queried to "attachment" as opposed to "bp_doc".

I've worked around it in the meantime by altering a few lines in the access-query.php but they aren't fit for a PR, so I'm leaving this here.

**Comment by boonebgorges** [comment] 2015-07-09 14:52
@trans1t Thanks so much for the report.

I'm unable to reproduce this in a simple test:

* As user 1, create a new Doc. Make sure the Doc has an attachment, and set the Read permission to "Doc author only".
* As user 2, go to `/docs/?has-attachment=yes`
* User 2 does *not* see the Doc listed

Looking at the code, the protection for `has-attachment=yes` is designed as follows:
1. `has-attachment=yes` filters the WP_Query object to include Docs with attachments in the `post__id` clause https://github.com/boonebgorges/buddypress-docs/blob/1.8.6/includes/attachments.php#L435-438
2. Docs with attachments should be limited to those that the current user has access to: https://github.com/boonebgorges/buddypress-docs/blob/1.8.6/includes/attachments.php#L449

I have a feeling one of two things is happening. One is that you have a plugin conflict - such as a plugin that modifies attachment queries at `pre_get_posts`. The other is that you've found a situation where the query protection described above isn't working properly. If it's the latter, then I'll need more details on your exact setup: who is the Doc author, what are the Doc privacy settings, who is the second user viewing the Doc (or is it an anonymous user), etc.

**Comment by trans1t** [comment] 2015-07-09 20:29
Thanks for trying to reproduce and the pointers to relevant code - I'll do some debugging and see if I can come up with more specific information for you.  I have disabled all plugins except buddypress & bp-docs but I'm running an older version of bp, perhaps that's related.  I'll report back in any case.

**Comment by christianwach** [comment] 2016-04-29 18:25
@boonebgorges I've just run into this issue and can verify that it does indeed happen.

Steps to reproduce on a clean install of branch 1.9.x:

1. Create two groups with one Doc per group with no attachments
2. Create a second user who only has membership of one group
3. For the Doc in the group user 2 is _not_ a member of, set the Doc visibility to "members only"
4. Visit "All Docs" page and filter by attachment
5. User 2 will see the Doc that they do not have access to
6. Toggling between "with attachment" and "without attachment" makes no difference - all Docs are visible

The problem here is basically the same as #425, in that `add_action( 'pre_get_posts', 'bp_docs_general_access_protection', 28 );` never fires on the "outer" query because the "outer" action is abandoned. A possible fix for this - which works for me - is to add a higher priority to the attachments filter, e.g. `add_action( 'pre_get_posts', array( $this, 'filter_directory_posts' ), 48 );`. Not sure what wider implications this may have.

There is a further issue when there are no Docs with attachments at all, in that `$post__in` remains empty, which leads to no filtering at all.

**Comment by boonebgorges** [comment] 2016-04-29 19:54
I've merged in the changes from #540. I'm going to mark this as complete, in the hopes that it is actually solved.

**Closed by boonebgorges** 2016-04-29 19:54 UTC

**Comment by christianwach** [comment] 2016-04-29 21:10
Thanks @boonebgorges I believe this does fix the problem. My only concern was that the attachment filter now comes _after_ the access filter and I'm not quite clear what ramifications that might have elsewhere.

The [WordPress ticket itself](https://core.trac.wordpress.org/ticket/17817) is 5 years old - wouldn't it be nice if it were resolved so we could avoid this kind of malarkey? Hey ho, I can understand the hesitation given how central to the WordPress ecosystem `$wp_filter` is.
