### ISSUE TITLE
Instructions to place Docs  into Menu

### ISSUE THREAD

**Issue by janvier269** [boonebgorges/buddypress-docs#513] opened 2016-03-02 16:23 UTC
Let me apologize in advance, if the following question is a known process in buddypress.   I am 44 and recently I was appointed to do this website for our abused condo association.  I was told buddypress is the best way to go; so I may be relying too much on plugins to do most of the scripting required.

We need to place in the main menu, "Docs | Pix | Vids" with a dropdown of the Categories, thus accessing only the related documents...  I could not find any documentation on how to do this with your plugin and I was hopping you can give me a hint where I can find such information or similar that I can learn from.

This is probably not the place to request this, but also I couldn't find a contact us, or any other way to  communicate this with you.

Thanks,
Janvier

**Comment by boonebgorges** [comment] 2017-11-18 20:59
Hi Janvier - Many apologies for not responding to this issue when it first came in. I'm going through old tickets and have just now seen this for the first time.

If you're still interested in implementing this, can you please give some details on exactly what it is that you're trying to do? When you say "main menu", what do you mean? Perhaps a screenshot would help, along with information about the theme you're using. If you're talking about items generated by `wp_nav_menu()` (which is what I suspect), then there are indeed ways to generate these links dynamically, though unfortunately it's not extremely straightforward. Here's a post I wrote on the subject a few years ago: https://teleogistic.net/2013/02/11/dynamically-add-items-to-a-wp_nav_menu-list/

You'd essentially need to create a top-level Docs item, and then query for the necessary Doc titles you want to show in the submenu before displaying. Exactly how this works depends on what you mean by "the Categories" and "the related documents".

**Comment by boonebgorges** [comment] 2017-11-18 21:00
(I'm going to close this issue because it is not a bug or feature request, but it's OK to continue posting here if you need pointers.)

**Closed by boonebgorges** 2017-11-18 21:00 UTC
